#!/usr/bin/env python3
"""Makes Android's launcher icons from design/nonya.png, in place of the Tauri defaults.

`npm run tauri icon` makes the desktop set, but its Android set is a square picture on a white
plate, which a launcher then crops to its own shape. Android 8 and later draw an *adaptive* icon
instead: a full-bleed layer of 108dp that the launcher masks to its shape — a circle, Samsung's
squircle — showing only the middle 72dp, with the part that must survive any mask inside the middle
66dp. So the artwork is placed on a canvas widened with its own navy, sized so the mark (the arch
and the road) sits inside that safe zone, and every mask shows navy around it:

  1. the black surround the artwork is painted on becomes the navy (a flood fill from the corners,
     so the artwork's own near-black body is left alone);
  2. the artwork is centred on a canvas of CANVAS pixels, the rest filled with BODY;
  3. that is the foreground at every density, over a BODY background colour, which is what shows if
     a launcher ever zooms the layer out.

Launchers older than Android 8 take the legacy icons: the desktop icon (src-tauri/icons/icon.png,
the prepared artwork on transparency) for the square one, and the adaptive layer cut to a circle
for the round one.

Needs Pillow (`pip install pillow`); it runs only when the artwork changes, so it is not a
dependency of the app.

    python3 scripts/android-icons.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "nonya.png"
LEGACY = ROOT / "src-tauri" / "icons" / "icon.png"
RES = ROOT / "src-tauri" / "gen" / "android" / "app" / "src" / "main" / "res"

# The artwork's body at its edges, sampled from nonya.png.
BODY = (8, 13, 38)
# The mark is about 805 of the artwork's 1254 pixels tall; 66dp of 108 is 61% of the canvas.
CANVAS = 1320

DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}


def adaptive_layer() -> Image.Image:
    art = Image.open(SOURCE).convert("RGB")
    for corner in [(0, 0), (art.width - 1, 0), (0, art.height - 1), (art.width - 1, art.height - 1)]:
        ImageDraw.floodfill(art, corner, BODY, thresh=24)
    canvas = Image.new("RGB", (CANVAS, CANVAS), BODY)
    canvas.paste(art, ((CANVAS - art.width) // 2, (CANVAS - art.height) // 2))
    return canvas


def circle(image: Image.Image) -> Image.Image:
    mask = Image.new("L", image.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0, image.width - 1, image.height - 1), fill=255)
    out = image.convert("RGBA")
    out.putalpha(mask)
    return out


def main() -> None:
    layer = adaptive_layer()
    # The legacy round icon is the visible middle 72dp of the layer, as an adaptive one would show.
    inset = round(CANVAS * 18 / 108)
    visible = layer.crop((inset, inset, CANVAS - inset, CANVAS - inset))
    legacy = Image.open(LEGACY).convert("RGBA")

    for name, scale in DENSITIES.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        fore = round(108 * scale)
        icon = round(48 * scale)
        layer.resize((fore, fore), Image.LANCZOS).save(folder / "ic_launcher_foreground.png")
        legacy.resize((icon, icon), Image.LANCZOS).save(folder / "ic_launcher.png")
        circle(visible.resize((icon, icon), Image.LANCZOS)).save(folder / "ic_launcher_round.png")

    adaptive = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/android-icons.py from design/nonya.png. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        "</adaptive-icon>\n"
    )
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(exist_ok=True)
    for name in ["ic_launcher.xml", "ic_launcher_round.xml"]:
        (anydpi / name).write_text(adaptive)

    (RES / "values" / "ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/android-icons.py: the artwork\'s body, behind its icon layer. -->\n'
        "<resources>\n"
        '    <color name="ic_launcher_background">#%02X%02X%02X</color>\n' % BODY
        + "</resources>\n"
    )
    print(f"wrote the Android launcher icons into {RES}")


if __name__ == "__main__":
    main()
