#!/usr/bin/env bash
# Arch Linux packaging, from the release .deb, for Arch, Manjaro and their kin, which cannot install
# a .deb.
#
#   ./scripts/package-arch.sh <Nunya_X.Y.Z_amd64.deb> [out-dir]
#       builds nunya-X.Y.Z-1-x86_64.pkg.tar.zst, for `pacman -U` (attached to every release)
#   ./scripts/package-arch.sh --aur <Nunya_X.Y.Z_amd64.deb> <out-dir>
#       writes the AUR's nunya-bin (PKGBUILD and .SRCINFO), which downloads that .deb from the
#       vX.Y.Z release and checks it against this one's SHA256; then builds it once, to prove it does
#
# Linux ships as packages only (docs/CONTRIBUTING.md, *Linux: packages, not an AppImage*), and VPN
# mode needs one: it is file capabilities on the bundled core (`platform/linux.rs`), granted only to
# a root-owned core beside a root-owned `Nunya` — a system package's /usr/bin.
#
# Why repackage the .deb rather than build again: it is the very build Debian users get, so the
# packages cannot drift, and Tauri has no pacman bundler. The .deb's file tree is installed as is;
# only the metadata is Arch's. The AUR package is the same PKGBUILD with the release as its source —
# the usual shape of a `-bin` package, and the AUR takes no binaries of its own.
#
# Needs makepkg (pacman's base-devel) and must not run as root, which makepkg refuses. CI runs it in
# an archlinux container as an unprivileged user (release.yml).

set -euo pipefail

AUR=0
if [[ "${1:-}" == "--aur" ]]; then
  AUR=1
  shift
fi
DEB="${1:?usage: package-arch.sh [--aur] <Nunya_X.Y.Z_amd64.deb> [out-dir]}"
OUT="${2:-$(dirname "$DEB")}"
[[ -f "$DEB" ]] || { echo "error: $DEB not found" >&2; exit 1; }
command -v makepkg >/dev/null || { echo "error: makepkg not found (pacman's base-devel)" >&2; exit 1; }

REPO="${GITHUB_REPOSITORY:-nunyavpn/nunya}"
# Nunya_0.5.1_amd64.deb → 0.5.1. pacman versions cannot hold '-'.
VERSION="$(basename "$DEB" | sed -E 's/^Nunya_([^_]+)_amd64\.deb$/\1/')"
[[ "$VERSION" != "$(basename "$DEB")" ]] || { echo "error: cannot read a version from $DEB" >&2; exit 1; }
PKGVER="${VERSION//-/_}"
SUM="$(sha256sum "$DEB" | cut -d' ' -f1)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if (( AUR )); then
  PKGNAME=nunya-bin
  # The release's own asset, named with its version so makepkg's cache never mixes two of them up.
  SOURCE="Nunya_\${pkgver}_amd64.deb::https://github.com/${REPO}/releases/download/v\${pkgver}/Nunya_\${pkgver}_amd64.deb"
  DEBFILE="Nunya_\${pkgver}_amd64.deb"
  EXTRA="provides=('nunya')
conflicts=('nunya')"
else
  PKGNAME=nunya
  SOURCE="nunya.deb"
  DEBFILE="nunya.deb"
  EXTRA=""
  cp "$DEB" "$WORK/nunya.deb"
fi

cat > "$WORK/PKGBUILD" <<EOF
# Generated by scripts/package-arch.sh from Nunya_${VERSION}_amd64.deb; edit that, not this.
# Maintainer: Nunya <https://github.com/${REPO}>
pkgname=${PKGNAME}
pkgver=${PKGVER}
pkgrel=1
pkgdesc="Desktop VPN client for nunya-core: VLESS, VMess, Trojan and WireGuard, as a VPN or a proxy"
arch=('x86_64')
url="https://github.com/${REPO}"
license=('GPL-3.0-only')
# What the .deb names (libwebkit2gtk-4.1-0, libgtk-3-0) in Arch's spelling, and libdbus for the
# tray's own StatusNotifierItem.
depends=('webkit2gtk-4.1' 'gtk3' 'dbus')
optdepends=(
  'polkit: VPN mode (asks for the password once)'
  'libcap: VPN mode (setcap gives the tunnel engine its network rights)'
)
${EXTRA}
# The core is a Go binary that the release pins by checksum; stripping it or splitting debug info
# gains nothing and rewrites it.
options=('!strip' '!debug')
source=("${SOURCE}")
noextract=("${DEBFILE}")
sha256sums=('${SUM}')

package() {
  bsdtar -xf "${DEBFILE}"
  bsdtar -xf data.tar.* -C "\$pkgdir"
}
EOF

mkdir -p "$OUT"
if (( AUR )); then
  # The release must already carry the .deb: makepkg downloads it, which is the check that the
  # PKGBUILD an AUR user gets actually builds.
  ( cd "$WORK" && makepkg --printsrcinfo > .SRCINFO && PKGDEST="$WORK/out" makepkg --nodeps --noconfirm --clean >/dev/null )
  cp "$WORK/PKGBUILD" "$WORK/.SRCINFO" "$OUT/"
  echo "$OUT/PKGBUILD"
else
  ( cd "$WORK" && PKGDEST="$WORK/out" makepkg --nodeps --noconfirm --clean >/dev/null )
  cp "$WORK"/out/*.pkg.tar.zst "$OUT/"
  ls "$OUT"/nunya-"$PKGVER"-*.pkg.tar.zst
fi
